### ISSUE TITLE
Exception after rebase

### ISSUE THREAD

**Issue by RobertPaasche** [NetworkedAssets/git4c#6]
After rebase a used branch the plugin throws the following exception
-Caused by: org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with files:

Workaround:
Deleting the cache folder.

**Comment by bartoszbednarekna** [comment]
Hello, we will take this issue with high prio into next release. Thank you very much for a bug report! After fixing that problem we will give you know about a result. 
Best, NA

**Comment by bartoszbednarekna** [comment]
The fix is present in Atlassian Marketplace with Git4C in version 1.3.1 

I hope that it will fix problems with rebase flow at your repository. 

That version will delete temp git folder in confluence automaticly if there is merging collision and will refresh a cache. In addition there is 3 times retry in background while fetching.

**Comment by RobertPaasche** [comment]
I will test it the next we rebase an relevant branch.

**Comment by RobertPaasche** [comment]
Seems to be fixed.
